### ISSUE TITLE
Activity - Build Dictionary

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#17]
User story: As an RPA Developer, I want to use an activity that allows me to build a Dictionary. The activity will build a dicitonary given the provided values.

**UiPath Activity Name**: Build Dictionary
**C# Method Name**: BuildDictionary

![001](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/1168856/4b391a6d-885b-4119-8604-b8e517065474)

**Comment by k2zinger** [comment]
Note:
This activity currently has a bug where it does not allow users to add keys/values to it.
![image](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/24416126/defd135f-412c-4910-b489-ecb56d3fc289)
**Resolving this bug should occur in a future wave.**

Implementation should be similar to:
myDictionary = new Dictionary<Object, Object>();
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.-ctor?view=net-7.0#system-collections-generic-dictionary-2-ctor
