### ISSUE TITLE
Activity - Clear Dictionary

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#18]
User story: As an RPA Developer, I want to use an activity that allows me to clear a Dictionary. The activity will clear the given Dictionary.

**UiPath Activity Name**: Clear Dictionary
**C# Method Name**: ClearDictionary

![002](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/1168856/844ec886-3358-415c-a4fd-6e120a136412)

**Comment by k2zinger** [comment]
Implementation should be similar to:
myDictionary.Clear();
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.clear?view=net-7.0
