### ISSUE TITLE
Activity - Dictionary Contains Key

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#20]
User story: As an RPA Developer, I want to use an activity that will determine if a specific Key exists within a given Dictionary. The activity will provide a Boolean results as to whether a provided Key exists within a provided Dictionary. When the given key exists, then value will be returned.  When the given key is does not exists, a null is returned for the value.
Acceptance Criteria: Include at least one unit test.
Acceptance Criteria: Include Studio Test projects for both legacy and windows projects.
Acceptance Criteria: Update readme file, functions names should be in alphabetical order.

**UiPath Activity Name**: Dictionary Contains Key
**C# Method Name**: DictionaryContainsKey

![004](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/1168856/500a629d-c14e-40ef-b3e5-f7cde5d5e39e)

**Comment by k2zinger** [comment]
Implementation should be similar to:
Boolean result = myDictionary.ContainsKey(myKey);
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.containskey?view=net-7.0

**Comment by rsearing** [comment]
I just updated the name of the function to be ContainsKey (to match original function name and keep it the same as Cathleen's "ContainsValue"
