### ISSUE TITLE
Activity - Dictionary: ContainsValue

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#21]
User story: As an RPA Developer, I want to use an activity that allows me to determine if a Dictionary contains a specific Value. The activity will return a Boolean if the provided Dictionary contains the given Value.

**UiPath Activity Name**: Dictionary Contains Value
**C# Method Name**: DictionaryContainsValue

![007](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/1168856/c86fdbde-3d3d-4c43-bf12-f190278519e0)

**Comment by k2zinger** [comment]
Implementation should be similar to:
Boolean result = myDictionary.ContainsValue(myValue);
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.containsvalue?view=net-7.0

**Comment by rsearing** [comment]
Just some small advice for @cathleenuipath  & @TomlinMichael  - (and I'm not sure where you're both at) - however, your methods are going to be nearly identical - other than Cathleen - you're looking for the Value (ie Dictionary.ContainsValue) and Michael's will be Key (ie Dictionary.ContainsKey)

**Comment by rsearing** [comment]
I just updated the name of the function to be ContainsValue(to match the original function name and keep it the same as Michael's "ContainsKey"

**Comment by cathleenuipath** [comment]
[celebrate]     Cathleen Runde reacted to your message:
________________________________
