### ISSUE TITLE
Activity - Dictionary to String

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#22]
User story: As an RPA Developer, I want to use an activity that allows me to represent a Dictionary as a String. The activity will present the given DIctionary as a String.

**UiPath Activity Name**: Dictionary to String
**C# Method Name**: DictionaryToString

**Comment by k2zinger** [comment]
Implementation should be similar to:
```
var items = myDictionary.Select(keyValuePair => keyValuePair.ToString());
return string.Join(", ", items);
```
https://www.techiedelight.com/convert-a-dictionary-to-a-string-in-csharp/
