### ISSUE TITLE
Activity - Get Dictionary Keys

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#23]
User story: As an RPA Developer, I want to use an activity that allows me to return a List(Of Object) of Keys from a Dictionary. The activity will return a List(Of Object) of Keys from a given Dictionary.

**UiPath Activity Name**: Get Dictionary Keys
**C# Method Name**: GetDictionaryKeys

**Comment by k2zinger** [comment]
Implementation should be similar to:
Dictionary<Object, Object>.KeyCollection keyColl = myDictionary.Keys;
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.keys?view=net-7.0

**Comment by JLongUiPathTAM** [comment]
No type exists in studio and the UiPath extension to create activities for Dictionary<Object, Object>.KeyCollection  This builds fine locally but when testing in studio will lock up studio as it doesn't recognize a keycollection

**Comment by mkuehn10** [comment]
Could you return a list instead like

```
List<string> keyList = new List<string>(myDictionary.Keys);
```

**Comment by k2zinger** [comment]
Let's change it to a List<Object> and ensure the documentation states that this is the case

**Comment by JLongUiPathTAM** [comment]
Yes, had it that way to start with. i'll move back to that.
