### ISSUE TITLE
Activity - Get Dictionary Value

### ISSUE THREAD

**Issue by rsearing** [UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities#24]
User story: As an RPA Developer, I want to use an activity that allows me to return a Value from a Dictionary. The activity will return a Value from a given dictionary with the provided Key.

**UiPath Activity Name**: Get Dictionary Value
**C# Method Name**: GetDictionaryValue

![005](https://github.com/UiPath-TAM-Team/UiPathTAMTeam.Extensions.Activities/assets/1168856/56932fe0-f198-414c-aec0-d408a9a2dcd0)

**Comment by k2zinger** [comment]
Implementation should be similar to:
Object myValue = myDictionary[myKey];
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.item?view=net-7.0
